### ISSUE TITLE
Deque initialisation using array similar repeating and count parameter

### ISSUE THREAD

**Issue by jumbopilot** [apple/swift-collections#120]
Implement initialiser of Deque<Double> to allow initialisation of Deque elements like available for Array(repeating: 0.0, count: 10).
The repeating parameter shall be setable to any Double for a number of elements as defined in count parameter.

A possible use case is:
`private var myTryOfCircularQueue: Deque<Double> = Deque(repeating: 0.0, count: 10)`

instead of:

`private var myTryOfCircularQueue: Deque<Double> = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
`

**Comment by lorentey** [comment]
Belated update: this is already a thing!

https://github.com/apple/swift-collections/blob/main/Sources/DequeModule/Deque%2BCollection.swift#L582

Please reopen if there is an issue with this implementation.
