### ISSUE TITLE
CocoaPods release

### ISSUE THREAD

**Issue by ypopovych** [apple/swift-collections#131]
Hi.

Thanks for the good library!
Can it be released on CocoaPods too?
We are working on the library which needs OrderedMaps but it has to be published on CocoaPods too. 

Thanks,
Yehor

**Comment by lorentey** [comment]
We currently provide full support for building this package with the Swift Package Manager and Xcode, as well as limited support for CMake (only for bootstrapping purposes within the Swift project, not for general use).

We have no plans to support additional build systems or package managers.

If these don't fit your use case, one option is to vendor the modules you need within your own project. (As always, make sure you follow the conditions of the license.)

**Comment by shauket** [comment]
I am using open source project that project not supporting SPM then how can i use atomics swift?

**Comment by denfromufa** [comment]
@lorentey do you have docs for command-line build with swiftpm in an Swift project?
