### ISSUE TITLE
OrderedSet has non-unique items

### ISSUE THREAD

**Issue by rowungiles** [apple/swift-collections#142]
I'm seeing non-unique elements in an OrderedSet.

```
 ▿ 17 : <Foo: 0x2835abb80>
  ▿ 18 : <Foo: 0x2835abb80>
```

```
(lldb) po storage.seen[18] == storage.seen[17]
true
```

### Information

- **Package version:** 1.0.2
- **Platform version:** 12.2
- **Swift version:** swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce
```
protocol Hashing: Hashable {
    var uuid: String { get }
}

extension Hashing {
    static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.uuid == rhs.uuid
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(uuid)
    }
}

final class Foo: Hashing {
    let uuid: String
}

```

```
actor Storage {
    private(set) var seen = OrderedSet<Foo>()

    func update(item: Foo) {
        seen.updateOrAppend(item)

        if conditionRequiringReordering {
            seen.remove(item)
            seen.append(item)
        }
    }
}
```

I've noticed that this isn't always reproducable.

If I do `OrderedSet(storage.seen.elements)` the duplicates are removed.

### Expected behavior
OrderedSet has all unique elements

### Actual behavior
OrderedSet has not got unique elements

**Comment by lorentey** [comment]
Is there any chance the `uuid` of the duplicate items have changed after the item got added to the collection?

I'm asking because `Foo` is a reference type, which can be prone to such mutations behind the back of the set. If a `uuid` of an existing item changes, then it will likely no longer be in the right hash table bucket, breaking the collection's invariants, and preventing it from being found.

**Comment by rowungiles** [comment]
Hey @lorentey modifying `uuid` is exactly what happens (by design). It seems your analysis of `will likely no longer be in the right hash table bucket` is correct and I'll look at an alternative implementation. Thank you.
