### ISSUE TITLE
Documentation of OrderedDictionary.merge suggests it doesn't preserve order

### ISSUE THREAD

**Issue by joethebro2022** [apple/swift-collections#145]
The documentation of `OrderedDictionary.merge` has an code example which seems to suggest that it does **not** preserve order. However, looking into the implementation of `merge`, it seems that it **does** preserve order. 

In addition, tests I've done and also the `OrderedDictionary` unit tests here seem to show that `OrderedDictionary.merge` **does** preserve order.

### Information

- **Package version:** 1.0.2
- **Platform version:** 12.3.1 (21E258)
- **Swift version:** swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: arm64-apple-macosx12.0

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce
Here is an excerpt from the code snippet coming from the **documentation built with Xcode**:
```
var dictionary: OrderedDictionary = ["a": 1, "b": 2]

// Keeping existing value for key "a":
dictionary.merge(zip(["a", "c"], [3, 4])) { (current, _) in current }
// ["b": 2, "a": 1, "c": 4]
```

You can see that the order of `b` and `a` are changed from the original dictionary.

However, these are not the results I get from running this. Running this code snippet, I get `[a: 1, b: 2, c: 4]`, which are the expected results and order is preserved. I ran this code about 20 times, to make sure that it wasn't a random result coming from the fact that Swift generates new hashes on reruns.

### Expected behavior
Documentation code example should show that `merge` **does** preserve order. The comment should probably say `[a: 1, b: 2, c: 4]` instead of `["b": 2, "a": 1, "c": 4]`.

### Actual behavior
Documentation code example implies that `merge` does **not** preserve order.
If the original dictionary was `["a": 1, "b": 2]`, and merging with `[("a", 3), ("c", 4)]` produces `["b": 2, "a": 1, "c": 4]`, then it seems to suggest that `merge` destroys the current order in the dictionary.

**Comment by lorentey** [comment]
I updated the `merge`, `merging`, `filter` and `mapValues` docs in #153, documenting the order of keys in the result.
