### ISSUE TITLE
Add `subscript(unsafe:)` to `OrderedSet` to mutate `_elements` via `_modify` when the index is available and the uniqueness invariant upheld

### ISSUE THREAD

**Issue by b8591340** [apple/swift-collections#154]
There’s seems to be no way to modify the `_elements` memory in place when we want to alter a property that does not partake in the `Equatable` and `Hashable` conformance. Specifically, I have a struct that’s compared and hashed only on the immutable `id`, so unless the struct itself is refactored to include other fields, no safety mishap appears to be possible.

```swift
if let index = set.firstIndex(of: element) {
    var element = set[index]
    element.nonHashedValue = …
    set.updateOrAppend(element)
}
```

```swift
if let index = set.firstIndex(of: element) {
    set[unsafe: index].nonHashedValue = …
}
```

**Comment by lorentey** [comment]
I get worried about introducing any API that allows violation of data structure invariants. (Although `OrderedSet.init(uncheckedUniqueElements:)` does exist.)

My usual recommendation is to use an OrderedDictionary in such cases, using the identifiers as keys. Would that work well in your use case?

If we did end up adding this, we should probably find a better subscript label than `unsafe` -- it's a bit to non-descriptive in this case. (There is a world of difference between this and, say, a subscript that disables bounds checking). Having the label also apply to getter invocations feels a bit strange, too. An alternative formulation would be for this to be a simple method that passes an inout item to a supplied closure, but that has its own drawbacks.

**Comment by andrew-lundy** [comment]
> I get worried about introducing any API that allows violation of data structure invariants. (Although `OrderedSet.init(uncheckedUniqueElements:)` does exist.)
> 
> My usual recommendation is to use an OrderedDictionary in such cases, using the identifiers as keys. Would that work well in your use case?
> 
> If we did end up adding this, we should probably find a better subscript label than `unsafe` -- it's a bit to non-descriptive in this case. (There is a world of difference between this and, say, a subscript that disables bounds checking). Having the label also apply to getter invocations feels a bit strange, too. An alternative formulation would be for this to be a simple method that passes an inout item to a supplied closure, but that has its own drawbacks.

:heavy_plus_sign:

**Comment by lorentey** [comment]
https://github.com/apple/swift-collections/issues/171 reminds me that `OrderedSet` already offers a couple ways up doing this:

```swift
// If you don't already have an index to the existing item:
items.update(with: newValue)

// If you have an index:
items.update(newValue, at: index)
```

The second form avoids a full hash table lookup, but it still does verify that the new value compares equal to the old one (to ensure data structure invariants). Both variants return the old value.

We're currently missing API for updating a value in place -- however, safety concerns likely prevent us from adding that anyway. (As we'd have no efficient way to compare against the old value.)
