### ISSUE TITLE
[OrderedCollections] Document Sorting as Stable

### ISSUE THREAD

**Issue by benrimmington** [apple/swift-collections#186]
There are three pairs of `sort(by:)` and `sort()` methods, documented with:

> The sorting algorithm is not guaranteed to be stable.

- `OrderedDictionary.Elements.sort(by:)`
- `OrderedDictionary.Elements.sort()`
- `OrderedDictionary.sort(by:)`
- `OrderedDictionary.sort()`
- `OrderedSet.sort(by:)`
- `OrderedSet.sort()`

Should these APIs be documented like the [SE-0372][] implementation?

[SE-0372]: <https://github.com/apple/swift-evolution/blob/main/proposals/0372-document-sorting-as-stable.md>

**Comment by lorentey** [comment]
Yep. I believe we can safely make this change in the next patch release, 1.0.4.

**Comment by lorentey** [comment]
Suggested fix is up at #201 -- cc @benrimmington.

**Comment by lorentey** [comment]
Fix is merged to release/1.0. The changes will propagate to `release/1.1` and `main` with the next (manual) merge.
