### ISSUE TITLE
[README.md] Fix markdown table and broken links

### ISSUE THREAD

**Issue by benrimmington** [apple/swift-collections#209]
<https://github.com/apple/swift-collections/blob/main/README.md>

**Expected:**

| Package version         | Swift version |
| ----------------------- | ------------- |
| swift-collections 1.0.x | >= Swift 5.3  |
| swift-collections 1.1.x | >= Swift 5.5  |

**Actual:**

> | Package version | Swift version | |---|---|---| | swift-collections 1.0.x | >= Swift 5.3 | | swift-collections 1.1.x | >= Swift 5.5 |

--------------------------------------------------------------------------------

<https://github.com/apple/swift-collections/blob/main/Documentation/Internals/README.md>

All the internal links are broken.

* Should the leading dot of each path be removed?
* The leading underscore of `_CollectionsTestSupport` is missing from each path.

**Comment by lorentey** [comment]
Well spotted, thank you!

**Comment by lorentey** [comment]
Closing as fixed -- #220 merges these changes to `main`, so all should be well now.
