### ISSUE TITLE
Obsolete `OrderedDictionary` Documentation

### ISSUE THREAD

**Issue by p16r** [apple/swift-collections#289]
The example provided in the documentation for `OrderedDictionary.index(forKey:)` discussion section ([OrderedDictionary.swift:257](https://github.com/apple/swift-collections/blob/1.0.4/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift#L257)) does not compile. Evidently it was deprecated in 0.0.6 and obsoleted in 1.0.0 ([OrderedDictionary+Deprecations.swift:20](https://github.com/apple/swift-collections/blob/1.0.4/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary%2BDeprecations.swift#L20)). The compiler error suggests using a different subscript, which the documentation should be using instead.

### Information

- **Package version:** `1.0.4`
- **Platform version:** macOS Ventura 13.3
- **Swift version:** 
  `swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)`
  `Target: arm64-apple-macosx13.0`

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce
* View documentation for `OrderedDictionary.index(forKey:)` 
* Execute the snippet provided in the discussion section.

### Expected behavior
Successful compilation and the code executes correctly.

### Actual behavior
Compiler error suggesting a different valid subscript.

**Comment by lorentey** [comment]
Fixed in #342! Thanks for reporting this.
