### ISSUE TITLE
Warnings when building the package.

### ISSUE THREAD

**Issue by HiddenJester** [apple/swift-collections#294]
Swift Collections 1.0.3 and 1.0.4 have warnings when incorporated into an Xcode 14.3.1 project. I see both:

`swift-collections/Sources/OrderedCollections/HashTable/_HashTable+UnsafeHandle.swift:487:14: 'assign(repeating:count:)' is deprecated: renamed to 'update(repeating:count:)'`
and
`swift-collections/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift:187:25: 'assign(repeating:count:)' is deprecated: renamed to 'update(repeating:count:)'`

There's a fix available that looks reasonable to me, but I haven't tried applying it yet.

### Information

- **Package version:** Seen on both 1.0.3 & 1.0.4.
- **Platform version:** macOS 13.4 (22F66) (Ventura)
- **Swift version:** 
```
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```
### Checklist

- [✅ ] If possible, I've reproduced the issue using the `main` branch of this package. (Well … I presume. I've only tried using the releases, but I'm presuming that the releases are the same code as in main.)
- [ ✅] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce
These warnings are visible in Xcode after a build, but you have to drill into the build logs a bit to see them. I noticed them originally in the output from our command line build script. This runs `xcodebuild archive` on the project using the collections, and the errors are in the output seen there..

### Expected behavior
I expected the Swift Package release to build without warnings.

### Actual behavior
Any attempt to link this project creates the two warnings listed above.

**Comment by lorentey** [comment]
This has been resolved in https://github.com/apple/swift-collections/pull/268. The fix is scheduled for the 1.0.5 milestone.

> Well … I presume. I've only tried using the releases, but I'm presuming that the releases are the same code as in main

That is an incorrect assumption.
