### ISSUE TITLE
OrderedSet append does not return the same type as insert

### ISSUE THREAD

**Issue by Frizlab** [apple/swift-collections#30]
The API for insert in an `OrderedSet` is
```swift
public mutating func insert(_ item: Element, at index: Index) -> (inserted: Bool, index: Index)
```

and the one for append is
```swift
public mutating func append(_ item: Element) -> (inserted: Bool, index: Int)
```

I understand the return types are technically the same because `Index` is `Int`, always, but from a semantic point of view, shouldn’t the append method return a `(inserted: Bool, index: Index)` tuple?

### Information

- **Package version:** Swift Collection `0.0.2`
- **Platform version:** macOS `11.3`
- **Swift version:**
```text
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.4.0
```

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce
N/A

### Expected behavior
`OrderedSet`’s `append` method to return `(inserted: Bool, index: Index)`.

### Actual behavior
It returns `(inserted: Bool, index: Int)`.

**Comment by lorentey** [comment]
The difference has no runtime or compile time effect, but I guess it does show up in generated interface descriptions.
