### ISSUE TITLE
API-NUMPY-METADATA

### ISSUE THREAD

**Issue by ShahriarNasseri** [apple/swift-collections#306]
Replace this paragraph with a description of your proposed feature. 
Please be sure to describe some concrete use cases for the new feature -- be as specific as possible.
Provide links to existing issues or external references/discussions, if appropriate.

**Comment by MaxDesiatov** [comment]
I don't think that the issue is clear enough to keep it open, while the description looks copy-pasted from a template. Feel free to reopen with more details provided.

**Comment by ShahriarNasseri** [comment]
It Recovered DP-1 of Modular apple swift RLP
