### ISSUE TITLE
OrderedDictionary decoding.

### ISSUE THREAD

**Issue by SVN93** [apple/swift-collections#310]
### Information

- **Package version:** 1.0.4
- **Swift version:** 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce
Try to decode an OrderedDictionary from this JSON:
```
"Value": {
    "SalespersonID": "SP0003",
    "Name": "Steve Church"
}
```
The original Dictionary [accepts](https://github.com/apple/swift/blob/802e63a7786fbf018bb83d3383ffa99e13661668/stdlib/public/core/Codable.swift#L5654) such a format, but the OrderedDictionary expects the array of the key-value pairs which is a serious limitation in decoding.

### Expected behavior
The OrderedDictionary should be decoded as a regular Dictionary.

### Actual behavior
Expected to decode Array<Any> but found a dictionary instead.

**Comment by lorentey** [comment]
`OrderedDictionary` needs to guarantee that the order of its items will not change during serialization/deserialization. This is not guaranteed by `Codable`'s keyed containers -- therefore they aren't suitable for use by `OrderedDictionary`.

Note that `Codable` is a common denominator archival solution, primarily intended for use where you don't care about the precise details of the serialized format. It is the Swift version of `NSCoding`, or [Python's `pickle`](https://docs.python.org/3/library/pickle.html). `Codable` is emphatically not a flexible JSON encoder/decoder that's designed to interoperate with arbitrary JSON APIs.

https://github.com/apple/swift-collections/issues/12#issuecomment-816277180
