### ISSUE TITLE
Invalid Windows Paths

### ISSUE THREAD

**Issue by SDGGiesbrecht** [apple/swift-collections#33]
Some files here and in swift‐collections‐benchmark contain paths that are invalid on Windows. As a result, SwiftPM cannot build swift‐collections _from_ Windows. (It can cross‐compile _to_ Windows just fine.)

```
[...]
Resolving https://github.com/apple/swift-collections at 0.0.2
[...]\.build\checkouts\swift-collections: error: Couldn’t check out revision ‘2d719d75a2065f213e58a5164384a3d2fcf9b59a’:
    error: invalid path 'Documentation/Announcement-benchmarks/Results/01 Deque: random access lookups.png'
[...]
Resolving https://github.com/apple/swift-collections-benchmark at 0.0.1
[...]\.build\checkouts\swift-collections-benchmark: error: Couldn’t check out revision ‘49297647d1c0855eb33ec18cd6ee1181727c159b’:
    error: invalid path 'Documentation/Assets/sample-results/01 Deque: random access lookups.png'
Error: Process completed with exit code 1.
```

### Information

- **Package version:** 0.0.2
- **Platform version:** Windows 10
- **Swift version:** Swift 5.4.0

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce

Simply attempt to check out each relevant repository on Windows. (An empty Windows GitHub action can be created to trigger a checkout attempt without a local Windows machine.)

**Comment by lorentey** [comment]
https://github.com/apple/swift-collections/pull/34 renamed these files in swift-collection, while https://github.com/apple/swift-collections-benchmark/pull/9 resolved the same issue in swift-collections-benchmark. Thank you all!

Additionally, https://github.com/apple/swift-collections-benchmark/pull/10 will prevent the benchmarking tool from trying to generate invalid filenames on Windows.
