### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by aiKrice** [apple/swift-collections#363]
According to https://developer.apple.com/support/third-party-SDK-requirements/
We need to have a Privacy manifest in this Lib (pretty strange to ask this from an Apple Repo :D )

**Comment by xwu** [comment]
This isn't a third-party SDK.

**Comment by lorentey** [comment]
Indeed, this package is not third-party SDK, and it isn't subject to these requirements.

(To be very clear, this package does not collect any information whatsoever, neither from end users nor developers. Nor does it use any required reason APIs.)

**Comment by lorentey** [comment]
(If you get feedback otherwise, let us know and we'll look into it!)

**Comment by rockbruno** [comment]
It certainly is, you can see from the list that they require manifests even for simple utilities like OrderedSet. So even though they used the term "third-party SDK", they clearly mean any type of code here. But if swift-collections doesn't use required reason APIs then it indeed doesn't need to do anything.

**Comment by lorentey** [comment]
The name `OrderedSet` in that list refers to a third-party code base ("SDK") of that name. 

It does not refer to the type `OrderedSet` in this package. This package is called "Swift Collections", or "swift-collections", and if it was a third-party SDK (which it most certainly isn't), then it would be listed under that name.

Again, please reach out to me if you get official App Store feedback that indicates otherwise.

**Comment by vanvoorden** [comment]
@lorentey Hmm… given the potential for confusion and ambiguity here on the part of developers… could we arrange to have that Apple Developer Support page updated with an explicit "allowlist" to make it clear that some Apple GitHub repos are safe to include without a privacy manifest? There's some signal here IMO that it would be helpful to document that and help make things more clear for developers.

**Comment by rockbruno** [comment]
@lorentey Yes, I am aware OrderedSet is a different package and that swift-collections doesn't need a manifest as of writing. I was just pointing that many of the "SDKs" in Apple's list are packages just like this one.
