### ISSUE TITLE
Circular Queue  

### ISSUE THREAD

**Issue by anantcodes** [apple/swift-collections#37]
Circular Queue is an extension of the Queue data structure in which the last item is connected with the first item or the first index comes right after the last index. We can consider it like a Ring Buffer.

[Circular Queue definition](https://www.geeksforgeeks.org/circular-queue-set-1-introduction-array-implementation/)

The same can be written in Swift as well using a Ring Buffer Extension.

The following code deals with Circular Queue:

`struct RingBufferQueue<T>: CustomStringConvertible {
    
    private var elements: [T?]
    private var front = -1
    private var rear = -1
    
    init(count: Int) {
        elements = Array(repeating: nil, count: count)
    }
    
    var isEmpty: Bool {
        front == -1 && rear == -1
    }
    
    var isFull: Bool {
        ((rear + 1) % elements.count) == front
    }
    
    var description: String {
        if isEmpty { return "Queue is empty..." }
        return "---- Queue start ----\n"
            + elements.map({String(describing: "\($0)")}).joined(separator: " -> ")
            + "\n---- Queue End ----\n"
    }
    
    var peek: T? {
        if isEmpty { return nil }
        return elements[front]
    }
}

extension RingBufferQueue {
    
    // to enqueue an element
    mutating func enqueue(_ element: T) -> Bool {
        
        // if queue is empty
        if front == -1 && rear == -1 {
            front = 0
            rear = 0
            elements[rear] = element
            return true
        }
        
        if isFull {
            print("QUEUE IS FULL")
            return false
        }
        
        rear = (rear + 1) % elements.count
        elements[rear] = element
        return true
    }
}

extension RingBufferQueue {
    
    // to dequeue an element
    mutating func dequeue() -> T? {
        
        if isEmpty {
            print("QUEUE IS EMPTY")
            return nil
        }
        
        // if queue has only single element
        if front == rear {
            defer {
                elements[front] = nil
                front = -1
                rear = -1
            }
            return elements[front]
        }
        
        defer {
            elements[front] = nil
            front = (front + 1) % elements.count
        }
        return elements[front]
    }
}
`

**Note :** Modifications can be made to the above code as it is generic in nature.

**Comment by kylemacomber** [comment]
[`Deque`](https://github.com/apple/swift-collections/blob/main/Documentation/Deque.md) is actually a circular queue backed by a ring buffer!

**Comment by anantcodes** [comment]
Okay , but can you please elaborate a bit on this?

**Comment by lorentey** [comment]
Like Kyle said, this package already implements this data structure.

The `enqueue` method corresponds to `Deque.append(_:)`, while `dequeue` corresponds to `Deque.removeFirst()`.

**Comment by anantcodes** [comment]
Okay got it. Thank you for briefing about the same.
