### ISSUE TITLE
Ambiguous use of 'initialize(fromContentsOf:)' in UnsafeMutableBufferPointer+Extras.Slice

### ISSUE THREAD

**Issue by JessyCatterwaul** [apple/swift-collections#387]
Collections doesn't compile with the first Xcode 16 beta.

`UnsafeMutableBufferPointer+Extras` has an `Ambiguous use of 'initialize(fromContentsOf:)'` error.

How should we get around this?

### Information

- **Package version:** `main`
- **Platform/Swift version:** swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

### Checklist

- ☑️  If possible, I've reproduced the issue using the `main` branch of this package.
- ☑️ I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

**Comment by JessyCatterwaul** [comment]
I see that this has gotten 6 thumbs ups, so it can't just be me, but haven't been able to whittle this down to what's necessary to reproduce the problem.

**Comment by lorentey** [comment]
This is the sort of source break that can be triggered by [SE-0437](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0437-noncopyable-stdlib-primitives.md); however, I am yet to see this actually happen.

SE-0437 did not generalize the standard `initialize(fromContentsOf:)` functions, though -- I'd expect such source compat regressions to only affect entry points that did get generalized. However, there may be some undiagnosed compiler regression.

If you're still seeing this with the current dev snapshots (and/or Xcode betas), reproduction steps would be very welcome. Please include the precise toolchain versions that exhibit the issue, as well as the raw compiler output, including verbatim copies of all diagnostic messages.

**Comment by lorentey** [comment]
I haven't heard back -- I assume this no longer reproduces with the final 6.0 release. Please reopen if you still see this.

**Comment by JiaheXu** [comment]
Hi, I have the same issue. The project is coded using xcode15.2, but it doe

<img width="1459" alt="Image" src="https://github.com/user-attachments/assets/fa31be7d-d960-47b3-9868-dfef1ba56b6e" />

sn't work with xcode16.

**Comment by JiaheXu** [comment]
> Hi, I have the same issue. The project is coded using xcode15.2, but it doe
> 
> <img alt="Image" width="1459" src="https://private-user-images.githubusercontent.com/48428720/406208544-fa31be7d-d960-47b3-9868-dfef1ba56b6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2NjU0NDIsIm5iZiI6MTczNzY2NTE0MiwicGF0aCI6Ii80ODQyODcyMC80MDYyMDg1NDQtZmEzMWJlN2QtZDk2MC00N2IzLTk4NjgtZGZlZjFiYTU2YjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIzVDIwNDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZTJjZjA0ZjFlMWNlZThmN2QyYWI5MzEwOWEyY2VlMGU0ZDA3OThhZmE1YzIxOThmYTNkN2NjNjFmMjk5MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f39-UzYURhdvilctAsKKjRe2POyrCdwYz01vEXyTyxA">
> sn't work with xcode16.

The compile error happened before compile my code

**Comment by LiaoChiawen** [comment]
> Hi, I have the same issue. The project is coded using xcode15.2, but it doesn't work with xcode16. I am using swift5 can swift-collection version 1.1.4
> 
> <img alt="Image" width="1459" src="https://private-user-images.githubusercontent.com/48428720/406208544-fa31be7d-d960-47b3-9868-dfef1ba56b6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc5OTc2OTUsIm5iZiI6MTczNzk5NzM5NSwicGF0aCI6Ii80ODQyODcyMC80MDYyMDg1NDQtZmEzMWJlN2QtZDk2MC00N2IzLTk4NjgtZGZlZjFiYTU2YjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI3VDE3MDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyOGE4NWY4ODFiOWE2MTRjYWEyYzAzMjY2OGM0OTFiODM4ZDg1NmU1MjQ4MDVmZDRmNjc1OTg0YjE3MWQ1ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yk976Jgp2k_Ozez9r4dPCBvTSi8CyhqHEAuw2GxpYfQ">
We are woking on the same app project and I met this problem too when using Xcode 16 and swift 6.x.x 😆 This issue is gone when I download and use Xcode 15.0
