### ISSUE TITLE
Conform `OrderedDictionary` to `Collection` by wrapping integer indices in a non-`Hashable` index type

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [apple/swift-collections#57]
This is likely a bad idea. I'm pitching it here on the off-chance that it might lead to a better solution.

Currently `OrderedDictionary ` is unable to conform to `Collection` because it's unable to implement `subscript(position:)`, which is because it conflicts with `subscript(key:)` when the dictionary's keys are of its index type (`Int`).

Meanwhile, `Dictionary` avoids this and conforms to `Collection` by using an index type that almost certainly won't be used for keys.

What if we do something similar for `OrderedDictionary `, while still using `Int` for actual indixing? One possible solution in my opinion is wrapping `Int` in a new `Index` type for only `Collection` requirements (#58):

```swift
extension OrderedDictionary: Collection {

  public struct Index: Comparable {
    public static func < (lhs: Self, rhs: Self) -> Bool {
      lhs.value < rhs.value
    }
    
    public init(value: Int) {
      self.value = value
    }
    
    public let value: Int
  }

  public var startIndex: Index {
    Index(value: _keys.startIndex)
  }

  public var endIndex: Index {
    Index(value: _keys.endIndex)
  }

  public func index(after i: Index) -> Index {
    Index(value: _keys.index(after: i.value))
  }

  public subscript(position: Index) -> (key: Key, value: Value) {
    get { (_keys[position.value], _values[position.value]) }
  }

}
```

Because `Index` in the above snippet does not conform to `Hashable`, it's guaranteed that it cannot be used as `Key`.

The disadvantage, though, is that with something like this, there will be 2 index types visible to the user:

```swift
let orderedDictionary: OrderedDictionary = [1: "a", 2: "b"]
print(orderedDictionary.index(forKey: 1)) // prints "0"
print(orderedDictionary.startIndex)       // prints "Index(value: 0)"
```

Although it's straightforward to convert between `Int` and `Index`, it can be a surprise and source of confusion to new users.

**Comment by lorentey** [comment]
This is not unreasonable, and in fact this is how `OrderedDictionary` was initially implemented. After using it for a while though, I had to agree with @kylemacomber that sticking to integer indices was the better design overall -- it feels more consistent and more convenient.

Having to type `dictionary.elements[i]` felt far less of a chore than `dictionary[Index(offset: i)]` (or even worse, `dictionary[dictionary.index(dictionary.startIndex, offsetBy: i)]`).
