### ISSUE TITLE
Bug in CheckCollection from CollectionsTestSupport?

### ISSUE THREAD

**Issue by notcome** [apple/swift-collections#59]
I am adopting `CollectionsTestSupport` code for my own testing purpose. I noticed that in `checkCollection`, `distance(from:to:)`, the testing code seems to get all possible pairs of all indices, rather than making sure that the first index is less or equal to the second one:

https://github.com/apple/swift-collections/blob/f1c6cb4a4f2867d575a4f105f1ca3100097db653/Sources/CollectionsTestSupport/ConformanceCheckers/CheckCollection.swift#L204-L210

I believe the documentation for Collection says:

```
Unless the collection conforms to the BidirectionalCollection protocol, start must be less than or equal to end.
```

So this is probably a bug? It causes issues for my non-bidirectional collections.

**Comment by lorentey** [comment]
Good catch! This is indeed a bug -- only the bidirectional checker should feed decreasing indices to `distance`.
